# gt_highlight_cols { #gt_extras.gt_highlight_cols }

```python
gt_highlight_cols(
    gt,
    columns=None,
    fill='#80bcd8',
    alpha=None,
    font_weight='normal',
    font_color='#000000',
)
```

Add color highlighting to one or more specific columns

The `gt_highlight_cols()` function takes an existing `GT` object and adds highlighting color
to the cell background of a specific column(s).

## Parameters {.doc-section .doc-section-parameters}

| Name        | Type                                                            | Description                                                                                                                                                                                                                                                                                               | Default     |
|-------------|-----------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------|
| gt          | GT                                                              | An existing `GT` object                                                                                                                                                                                                                                                                                   | _required_  |
| columns     | SelectExpr                                                      | The columns to target. Can either be a single column name or a series of column names provided in a list. If `None`, the alignment is applied to all columns.                                                                                                                                             | `None`      |
| fill        | str                                                             | A character string indicating the fill color. If nothing is provided, then `"#80bcd8"` (light blue) will be used as a default.                                                                                                                                                                            | `'#80bcd8'` |
| alpha       | int \| None                                                     | An integer `[0, 1]` for the alpha transparency value for the color as single value in the range of `0` (fully transparent) to `1` (fully opaque). If not provided the fill color will either be fully opaque or use alpha information from the color value if it is supplied in the `"#RRGGBBAA"` format. | `None`      |
| font_weight | Literal\[\'normal\', \'bold\', \'bolder\', \'lighter\'\] \| int | A string or number indicating the weight of the font. Can be a text-based keyword such as `"normal"`, `"bold"`, `"lighter"`, `"bolder"`, or, a numeric value between `1` and `1000`, inclusive. Note that only variable fonts may support the numeric mapping of weight.                                  | `'normal'`  |
| font_color  | str                                                             | A character string indicating the text color. If nothing is provided, then `"#000000"` (black) will be used as a default.                                                                                                                                                                                 | `'#000000'` |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                                                                                  |
|--------|--------|------------------------------------------------------------------------------------------------------------------------------|
|        | GT     | The `GT` object is returned. This is the same object that the method is called on so that we can facilitate method chaining. |

## Examples {.doc-section .doc-section-examples}

```{python}
from great_tables import GT, md
from great_tables.data import gtcars
import gt_extras as gte

gtcars_mini = gtcars[["model", "year", "hp", "trq"]].head(5)

gt = (
    GT(gtcars_mini, rowname_col="model")
    .tab_stubhead(label=md("*Car*"))
)

gte.gt_highlight_cols(gt, columns="hp")
```