# API Reference {.doc .doc-index}

## Themes

Functions to generate themes.

| | |
| --- | --- |
| [gt_theme_538](gt_theme_538.qmd#gt_extras.gt_theme_538) | Applies a FiveThirtyEight-inspired theme to a GT table. |
| [gt_theme_espn](gt_theme_espn.qmd#gt_extras.gt_theme_espn) | Applies an ESPN-inspired theme to a GT table. |
| [gt_theme_guardian](gt_theme_guardian.qmd#gt_extras.gt_theme_guardian) | Applies a Guardian-inspired theme to a GT table. |
| [gt_theme_nytimes](gt_theme_nytimes.qmd#gt_extras.gt_theme_nytimes) | Applies a New York Times-inspired theme to a GT table. |
| [gt_theme_excel](gt_theme_excel.qmd#gt_extras.gt_theme_excel) | Applies an Excel-inspired theme to a GT table. |
| [gt_theme_dot_matrix](gt_theme_dot_matrix.qmd#gt_extras.gt_theme_dot_matrix) | Applies a dot-matrix-inspired theme to a GT table. |
| [gt_theme_dark](gt_theme_dark.qmd#gt_extras.gt_theme_dark) | Applies a dark mode theme to a GT table. |
| [gt_theme_pff](gt_theme_pff.qmd#gt_extras.gt_theme_pff) | Applies a Pro Football Focus (PFF)-inspired theme to a GT table. |

## Utilities



| | |
| --- | --- |
| [gt_highlight_cols](gt_highlight_cols.qmd#gt_extras.gt_highlight_cols) | Add color highlighting to one or more specific columns. |